---
- name: Include Playbook
  hosts: all
  become: yes

  vars:
    mytext: "Privet from ROMAN"

  tasks:
  - name: ping test
    ping:

  - name: Create folders
    include_tasks: create_folders.yml
  - name: Create files
    include_tasks: create_files.yml
