---
- name:  My delegate playbook
  hosts: all
  become: yes

  vars:
   mytext: "Hello from Roman!"

  tasks:
  - name: Ping test
    ping:

  - name: Unregister Server From Load Balancer
    shell: echo This server {{ inventory_hostname }} was derigestered from our LoadBalancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1

  - name: Update my DB
    shell: echo UPDATING Database
    run_once: true

  - name:
    copy:
      dest: /home/file1.txt
      content: |
       This is FileN1
       On English Hello World
       On Russian {{ mytext }}
    delegate_to: AnsibleHost1
  
  - name:
    copy:
      dest: /home/file2.txt
      content: |
       This is FileN2
       On English Hello World
       On Russian {{ mytext }}

  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till my servers will come up online
    wait_for:
        host: "{{ ansible_host }}"
        state: started
        port: 22
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1
